name: Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - name: install goreleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          version: "~> v2"
          args: release --snapshot --clean

      - name: integration tests
        working-directory: ./e2e
        run: go test -v -ginkgo.v -timeout 3600s --ginkgo.label-filter=integration
